# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slamapp', '0003_auto_20170917_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.EmailField(max_length=70)),
                ('question_1', models.CharField(blank=True, max_length=2000)),
                ('answer_1', models.CharField(blank=True, max_length=2000)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='UserProfile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profiles'},
        ),
    ]
