# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slamapp', '0004_auto_20170918_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AddField(
            model_name='set',
            name='answer_10',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 10'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_11',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 11'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_12',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 12'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_13',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 13'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_14',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 14'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_15',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 15'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_16',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 16'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_17',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 17'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_18',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 18'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_19',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 19'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_2',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 2'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_20',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 20'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_3',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 3'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_4',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 4'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_5',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 5'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_6',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 6'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_7',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 7'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_8',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 8'),
        ),
        migrations.AddField(
            model_name='set',
            name='answer_9',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 9'),
        ),
        migrations.AddField(
            model_name='set',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='set',
            name='question_10',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 10'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_11',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 11'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_12',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 12'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_13',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 13'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_14',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 14'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_15',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 15'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_16',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 16'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_17',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 17'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_18',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 18'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_19',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 19'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 2'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_20',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 20'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_3',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 3'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_4',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 4'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_5',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 5'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_6',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 6'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_7',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 7'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_8',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 8'),
        ),
        migrations.AddField(
            model_name='set',
            name='question_9',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 9'),
        ),
        migrations.AddField(
            model_name='set',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pics', verbose_name='Profile Picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='answer_1',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Answer 1'),
        ),
        migrations.AlterField(
            model_name='set',
            name='question_1',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Question 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
    ]
