# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slamapp', '0005_auto_20170918_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=4000, verbose_name='Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_10',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_11',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_12',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_13',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_14',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_15',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_16',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_17',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_18',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_19',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_20',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_6',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_7',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_8',
        ),
        migrations.RemoveField(
            model_name='set',
            name='answer_9',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_10',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_11',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_12',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_13',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_14',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_15',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_16',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_17',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_18',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_19',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_20',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_5',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_6',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_7',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_8',
        ),
        migrations.RemoveField(
            model_name='set',
            name='question_9',
        ),
        migrations.AddField(
            model_name='set',
            name='filler_key',
            field=models.CharField(default=1, max_length=30, verbose_name='Filler Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='set_content',
            name='set_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slamapp.Set'),
        ),
    ]
