# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slamapp', '0005_auto_20170918_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
