# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slamapp', '0006_auto_20171001_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.EmailField(max_length=70)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=4000, verbose_name='Answer')),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slamapp.Set')),
            ],
        ),
    ]
