# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slamapp', '0006_auto_20170929_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlist_requests_created', to='slamapp.UserProfile')),
                ('my_user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlist_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
