# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slamapp', '0007_set_set_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set_content',
            old_name='sets',
            new_name='set_main',
        ),
    ]
