# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slamapp', '0008_auto_20171001_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='filler_key',
            field=models.CharField(default=1, max_length=30, verbose_name='Filler Key'),
            preserve_default=False,
        ),
    ]
